<script lang="ts">
  /**
   * FilenameImportButton.svelte
   * Triggers a browser prompt to paste a filename (with coordinates)
   * and extracts them for image sources.
   */
  import { parseFilenameCoords } from './utils.ts';

  let {
    onimport
  }: {
    onimport: (coords: [number, number][]) => void;
  } = $props();

  function handleAddFilename() {
    const input = prompt(
      `Paste a filename with coordinates generated by the builder (e.g. builder.-27.472667,153.023245,-27.481308,153.033005.png)`
    );

    if (input === null || input.trim() === '') return;

    const result = parseFilenameCoords(input);

    if (result) {
      onimport(result);
    } else {
      alert('Could not find valid coordinates in the provided filename.');
    }
  }
</script>

<button type="button" onclick={handleAddFilename}>Paste filename...</button>
